version: '3.7'

services:
  lemonbot:
    image: lemonsaurus/tyrant:latest
    container_name: tyrant
    command: pipenv run bot
    restart: always
    environment:
      - LEMONSAURUS_DISCORD_TOKEN=${LEMONSAURUS_DISCORD_TOKEN}
      - LEMONSAURUS_LOG_WEBHOOK=${LEMONSAURUS_LOG_WEBHOOK}
